version: '3'

services:
  frpc-ssh:
    container_name: ngxin-rtmp
    image: jasonrivers/nginx-rtmp
    restart: always
    ports:
      - "1935:1935"
      - "8080:8080"
    environment:
      - RTMP_STREAM_NAMES=live,teststream1,teststream2
      - RTMP_PUSH_URLS=rtmp://live.youtube.com/test/streamkey,rtmp://live.twitch.tv/app/streamkey
