version: '3'

services:
  frpc-ssh:
    container_name: frpc-ssh
    image: v7lin/frpc
    restart: always
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
    command:
      - "tcp"
      - "--proxy_name=frpc-ssh"
      - "--local_ip=192.168.0.110"
      - "--local_port=22" # 没有默认值
      - "--remote_port=6000" # TODO 为不同机器分配不同端口
      - "--server_addr=${FRP_SERVER_DOMAIN:-host.docker.internal}:7000"
      - "--token=${FRP_TOKEN:-frp}"
      - "--log_level=info"

  frpc-ssh-6001:
    container_name: frpc-ssh-6001
    image: v7lin/frpc
    restart: always
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
    command:
      - "tcp"
      - "--proxy_name=frpc-ssh-6001"
      - "--local_ip=192.168.0.110"
      - "--local_port=22" # 没有默认值
      - "--remote_port=6001" # TODO 为不同机器分配不同端口
      - "--server_addr=${FRP_SERVER_DOMAIN:-host.docker.internal}:7000"
      - "--token=${FRP_TOKEN:-frp}"
      - "--log_level=info"
#   test:
#     container_name: test
#     image: nginx:1.15.8-alpine
#     restart: always
# #    ports:
# #      - 80
#     environment:
#       - TZ=${TIME_ZONE:-Asia/Shanghai}

#   test-frpc:
#     container_name: test-frpc
#     image: v7lin/frpc
#     restart: always
#     environment:
#       - TZ=${TIME_ZONE:-Asia/Shanghai}
#     command:
#       - "http"
#       - "--proxy_name=test"
#       - "--local_ip=test"
#       - "--local_port=80"
# #      - "--sd=test" # subdomain
#       - "--custom_domain=test.${SERVER_DOMAIN:-localhost}"
#       - "--server_addr=${FRP_SERVER_DOMAIN:-host.docker.internal}:7000"
#       - "--token=${FRP_TOKEN:-frp}"
#       - "--log_level=trace"
#     depends_on:
#       - test



#  frps:
#    image: v7lin/frps
#    ports:
#      - 80:80 # vhost - http
#      - 443:443 # vhost - https
#      - 6000-6010:6000-6010 # ssh
#      - 7000:7000 # bind
#      - 7500:7500 # dashboard
#    environment:
#      - TZ=${TIME_ZONE:-Asia/Shanghai}
#    command:
#      - "--log_level=info"
#      - "--token=${FRP_TOKEN:-frp}"
#      - "--dashboard_port=7500" # 没有默认值
#      - "--dashboard_user=${FRP_DASHBOARD_USER:-frp}"
#      - "--dashboard_pwd=${FRP_DASHBOARD_PWD:-frp}"
#      - "--vhost_http_port=80"
#      - "--vhost_https_port=443"
#      - "--subdomain_host=frp.${SERVER_DOMAIN:-localhost}"